AspNetCore.Docs-main/aspnetcore/fundamentals/logging/loggermessage/samples/3.x/LoggerMessageSample/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoggerMessageSample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AspNetCore.Docs-main/aspnetcore/fundamentals/logging/loggermessage/samples/3.x/LoggerMessageSample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using LoggerMessageSample.Data;
using LoggerMessageSample.Internal;

namespace LoggerMessageSample.Pages
{
    public class IndexModel : PageModel
    {
        #region snippet1
        private readonly AppDbContext _db;
        private readonly ILogger _logger;

        public IndexModel(AppDbContext db, ILogger<IndexModel> logger)
        {
            _db = db;
            _logger = logger;
        }
        #endregion

        [BindProperty]
        public Quote Quote { get; set; }

        public IList<Quote> Quotes { get; private set; }

        #region snippet2
        public async Task OnGetAsync()
        {
            _logger.IndexPageRequested();

            Quotes = await _db.Quotes.AsNoTracking().ToListAsync();
        }
        #endregion

        #region snippet3
        public async Task<IActionResult> OnPostAddQuoteAsync()
        {
            _db.Quotes.Add(Quote);
            await _db.SaveChangesAsync();

            _logger.QuoteAdded(Quote.Text);

            return RedirectToPage();
        }
        #endregion

        #region snippet4
        public async Task<IActionResult> OnPostDeleteAllQuotesAsync()
        {
            var quoteCount = await _db.Quotes.CountAsync();

            using (_logger.AllQuotesDeletedScope(quoteCount))
            {
                foreach (Quote quote in _db.Quotes)
                {
                    _db.Quotes.Remove(quote);

                    _logger.QuoteDeleted(quote.Text, quote.Id);
                }
                await _db.SaveChangesAsync();
            }

            return RedirectToPage();
        }
        #endregion

        #region snippet5
        public async Task<IActionResult> OnPostDeleteQuoteAsync(int id)
        {
            try
            {
                var quote = await _db.Quotes.FindAsync(id);
                _db.Quotes.Remove(quote);
                await _db.SaveChangesAsync();

                _logger.QuoteDeleted(quote.Text, id);
            }
            catch (NullReferenceException ex)
            {
                _logger.QuoteDeleteFailed(id, ex);
            }

            return RedirectToPage();
        }
        #endregion
    }
}

AspNetCore.Docs-main/aspnetcore/fundamentals/logging/loggermessage/samples/3.x/LoggerMessageSample/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "LoggerMessage Sample";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Instructions</h3>
        </div>
        <div class="panel-body">
            <ol>
                <li>
                    On a GET request for this page, the logger logs a message:
                    <pre><code>info: LoggerMessageSample.Pages.IndexModel[1]
=> RequestId:0HL90M6E7PHK4:00000001 RequestPath:/ => /Index
GET request for Index page</code></pre>
                </li>
                <li>
                    Add a message.
                </li>
                <li>
                    The console indicates the logged message for the add operation:
                    <pre><code>info: LoggerMessageSample.Pages.IndexModel[2]
=> RequestId:0HL90M6E7PHK5:0000000A RequestPath:/ => /Index
Quote added (Quote = 'You can avoid reality, but you cannot avoid the consequences of avoiding reality. - Ayn Rand')</code></pre>
                </li>
                <li>
                    Delete the quote using its <b>Delete</b> button.
                </li>
                <li>
                    The console shows a log entry for the delete opertion:
                    <pre><code>info: LoggerMessageSample.Pages.IndexModel[4]
=> RequestId:0HL90M6E7PHK5:00000016 RequestPath:/ => /Index
Quote deleted (Quote = 'You can avoid reality, but you cannot avoid the consequences of avoiding reality. - Ayn Rand' Id = 1)</code></pre>
                <li>
                    Add three quotes.
                </li>
                <li>
                    Select the <b>Clear All</b> button.
                </li>
                <li>
                    The console includes the scope message:
                    <pre><code>info: LoggerMessageSample.Pages.IndexModel[4]
=> RequestId:0HL90MKUCAN0A:0000000A RequestPath:/ => /Index => All quotes deleted (Count = 3)
Quote deleted (Quote = 'Quote 1' Id = 1)
info: LoggerMessageSample.Pages.IndexModel[4]
=> RequestId:0HL90MKUCAN0A:0000000A RequestPath:/ => /Index => All quotes deleted (Count = 3)
Quote deleted (Quote = 'Quote 2' Id = 2)
info: LoggerMessageSample.Pages.IndexModel[4]
=> RequestId:0HL90MKUCAN0A:0000000A RequestPath:/ => /Index => All quotes deleted (Count = 3)
Quote deleted (Quote = 'Quote 3' Id = 3)</code></pre>
                </li>
            </ol>
        </div>
    </div>

    <form method="post">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add a quote</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label asp-for="Quote.Text"></label>
                    <input asp-for="Quote.Text" class="form-control" style="width:100%;margin-bottom:5px">
                </div>
                <div class="form-group">
                    <button type="submit" asp-page-handler="AddQuote" class="btn btn-default">Add Quote</button>
                </div>
            </div>
        </div>
    </form>

    <form method="post">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <button type="submit" asp-page-handler="DeleteAllQuotes" class="pull-right btn btn-danger">Clear All</button>
                <h3 class="panel-title" style="line-height:2.1">Quotes</h3>
            </div>
            <div class="panel-body">
                <ol>
                    @foreach (var quote in Model.Quotes)
                    {
                        <li>
                            <button type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteQuote" asp-route-id="@quote.Id">Delete</button>
                            <p style="line-height:2.5">@quote.Text</p>
                        </li>
                    }
                </ol>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <form method="post">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" style="line-height:2.1">Log an exception</h3>
            </div>
            <div class="panel-body">
                <ol>
                    <li>
                        A quote with an <code>Id = 999</code> doesn't exist in the database. The sample app surrounds the call to <code>_db.Quotes.FindAsync(id)</code> in a <code>try</code>-<code>catch</code> block. When <code>FindAsync</code> throws an <code>ArgumentNullException</code>, the <code>QuoteDeleteFailed</code> method is triggered on the logger.
                    </li>
                    <li>
                        Select the <b>Delete (Id = 999)</b> button and examine the console log for the message, which includes the <code>ArgumentNullException</code>.
                        <pre><code>LoggerMessageSample.Pages.IndexModel: Error: Quote delete failed (Id = 999)

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at LoggerMessageSample.Pages.IndexModel.OnPostDeleteQuoteAsync(Int32 id) in c:\Users\guard\Documents\GitHub\Docs\aspnetcore\fundamentals\logging\loggermessage\samples\3.x\LoggerMessageSample\Pages\Index.cshtml.cs:line 77</code></pre>
                    </li>
                </ol>
                <button type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteQuote" asp-route-id="999">Delete (Id = 999)</button>
            </div>
        </div>
    </form>
</div>